### ISSUE TITLE
Card style discrepancies

### ISSUE THREAD

**Issue by dabowman** [Automattic/vip-design-system#292]
I noticed that the border radius being called in the theme file is `borderRadius: 2` 

https://github.com/Automattic/vip-design-system/blob/21bf8d64e25104bd81dc974b3e212e436f9eda7b/src/system/theme/index.js#L250

This should resolve as 4px but the border radius in Figma and in Storybook is 8px. It's displaying correctly but I'm not sure where the value is coming from. 

Also, not sure what `backgroundMuted` is or where it's coming from. We should replace with a standard token value. 

https://github.com/Automattic/vip-design-system/blob/21bf8d64e25104bd81dc974b3e212e436f9eda7b/src/system/theme/index.js#L265

**Comment by djalmaaraujo** [comment]
@dabowman When you say "standard token value", please refer to the token name. Can you tell me the token value for the replacement of the backgroundMuted?
