### ISSUE TITLE
Autocomplete updates

### ISSUE THREAD

**Issue by emaurer11** [Automattic/vip-design-system#314]
P2 proposal for this update is here: https://pixelsandpointsp2.wordpress.com/2023/11/07/product-design-system-autocomplete-update/

Once the details are finalized, I'll update this issue with more specifics around this request.

**Comment by djalmaaraujo** [comment]
A few notes:

- We need to move all customizations stories to a single story, avoiding confusion;
- Add a proper Docs page to the Select component, maybe include Select and Autocomplete in the same Storybook examples, but explain when to use each one;
- Investigate if we can apply icons and labels, custom HTML to the options
- Check if the current autocomplete component supports `optgroup`

**Comment by djalmaaraujo** [comment]
I discussed with @emaurer11 the importance of waiting for the definition from the A8C wide-table component. We will get back to this issue later.
