### ISSUE TITLE
Add sort columns to tables

### ISSUE THREAD

**Issue by emaurer11** [Automattic/vip-design-system#340]
We need to add sorting columns as a feature of the table component. 

**How this should work**

- Sortable table columns should display a sort icon inline with the column name (see design)
- When a user clicks the column name, it should re-order the table rows based on the selected column

Design

- The design required for this feature is pretty minimal. A good start on the design can be found here:
https://www.figma.com/file/jcGe2KIAlh2PxaAZ5liYWi/Productive-Components?type=design&node-id=8553%3A4382&mode=design&t=d6l7x42IawTmh4Ry-1

**Comment by djalmaaraujo** [comment]
I discussed with @emaurer11 the importance of waiting for the definition from the A8C wide-table component. We will get back to this issue later.
